// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pctp.Data;

#nullable disable

namespace pctp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pctp.Models.Libro", b =>
                {
                    b.Property<string>("Titolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<string>("Autore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Titolo");

                    b.ToTable("Libri");

                    b.HasData(
                        new
                        {
                            Titolo = "Dune",
                            Anno = 1965,
                            Autore = "Frank Herbert",
                            Genere = "Fantascienza",
                            Img = "https://m.media-amazon.com/images/I/511suynbMfL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484100"
                        },
                        new
                        {
                            Titolo = "Messia di Dune",
                            Anno = 1969,
                            Autore = "Frank Herbert",
                            Genere = "Fantascienza",
                            Img = "https://m.media-amazon.com/images/I/41dbYUr0rUL.jpg",
                            Isbn = "9783161484101"
                        },
                        new
                        {
                            Titolo = "I figli di Dune",
                            Anno = 1976,
                            Autore = "Frank Herbert",
                            Genere = "Fantascienza",
                            Img = "https://m.media-amazon.com/images/I/412FZmYY0sL.jpg",
                            Isbn = "9783161484102"
                        },
                        new
                        {
                            Titolo = "L'imperatore-dio di Dune",
                            Anno = 1981,
                            Autore = "Frank Herbert",
                            Genere = "Fantascienza",
                            Img = "https://m.media-amazon.com/images/I/41R38uCEyGL.jpg",
                            Isbn = "9783161484103"
                        },
                        new
                        {
                            Titolo = "Gli eretici di Dune",
                            Anno = 1984,
                            Autore = "Frank Herbert",
                            Genere = "Fantascienza",
                            Img = "https://m.media-amazon.com/images/I/71yxc8fLNgL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484104"
                        },
                        new
                        {
                            Titolo = "La rifondazione di Dune",
                            Anno = 1985,
                            Autore = "Frank Herbert",
                            Genere = "Fantascienza",
                            Img = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfYGgvx44ivyiIuNymh8hWpBMpRBWI0HbrQg&s",
                            Isbn = "9783161484105"
                        },
                        new
                        {
                            Titolo = "Dune: The Battle of Corrin",
                            Anno = 2004,
                            Autore = "Brian Herbert",
                            Genere = "Fantascienza",
                            Img = "https://m.media-amazon.com/images/I/81tNTZMlczL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484106"
                        },
                        new
                        {
                            Titolo = "I cacciatori di Dune",
                            Anno = 2006,
                            Autore = "Brian Herbert",
                            Genere = "Fantascienza",
                            Img = "https://www.ibs.it/images/9788834740378_0_424_0_75.jpg",
                            Isbn = "9783161484107"
                        },
                        new
                        {
                            Titolo = "I vermi della sabbia di Dune",
                            Anno = 2007,
                            Autore = "Brian Herbert",
                            Genere = "Fantascienza",
                            Img = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXpiuDCTdxqD3xwJgKUbl3NYk0tl3Xd3QEmA&s",
                            Isbn = "9783161484108"
                        },
                        new
                        {
                            Titolo = "Harry Potter e la pietra filosofale",
                            Anno = 1997,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/51CgZFxNQ0L.jpg",
                            Isbn = "9783161484109"
                        },
                        new
                        {
                            Titolo = "Harry Potter e la camera dei segreti",
                            Anno = 1998,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/51KHFmcWGxL.jpg",
                            Isbn = "9783161484110"
                        },
                        new
                        {
                            Titolo = "Harry Potter e il prigioniero di Azkaban",
                            Anno = 1999,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/71LUEWuecxL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484111"
                        },
                        new
                        {
                            Titolo = "Harry Potter e il calice di fuoco",
                            Anno = 2000,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/71WfG8FffsL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484112"
                        },
                        new
                        {
                            Titolo = "Harry Potter e l'Ordine dellaFenice",
                            Anno = 2003,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/81GfdgEiHyL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484113"
                        },
                        new
                        {
                            Titolo = "Harry Potter e il Principe Mezzosangue",
                            Anno = 2005,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/710OqzcvPML._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484114"
                        },
                        new
                        {
                            Titolo = "Harry Potter e i doni della morte",
                            Anno = 2007,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/51Qr0XQQPXL.jpg",
                            Isbn = "9783161484115"
                        },
                        new
                        {
                            Titolo = "Harry Potter e la maledizione dell'erede",
                            Anno = 2016,
                            Autore = "J. K. Rowling",
                            Genere = "Fantasy",
                            Img = "https://m.media-amazon.com/images/I/81pwzk0tilL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484116"
                        },
                        new
                        {
                            Titolo = "Jurassic Park",
                            Anno = 1990,
                            Autore = "Michael Crichton",
                            Genere = "Fantascienza",
                            Img = "https://m.media-amazon.com/images/I/51KDF4N3J5L._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484117"
                        },
                        new
                        {
                            Titolo = "V for vendetta",
                            Anno = 1982,
                            Autore = "Alan Moore",
                            Genere = "Distopia",
                            Img = "https://m.media-amazon.com/images/I/81Aw7JnvLTL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484118"
                        },
                        new
                        {
                            Titolo = "Il nome della rosa",
                            Anno = 1980,
                            Autore = "Umberto Eco",
                            Genere = "Giallo",
                            Img = "https://m.media-amazon.com/images/I/61Aa9Yic8AL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484119"
                        },
                        new
                        {
                            Titolo = "Le avventure di Sherlock Holmes",
                            Anno = 1892,
                            Autore = "Arthur Conan Doyle",
                            Genere = "Giallo",
                            Img = "https://m.media-amazon.com/images/I/51yGQ7QMW8L.jpg",
                            Isbn = "9783161484120"
                        },
                        new
                        {
                            Titolo = "Il ritorno di Sherlock Holmes",
                            Anno = 1905,
                            Autore = "Arthur Conan Doyle",
                            Genere = "Giallo",
                            Img = "https://m.media-amazon.com/images/I/51L6qiJg1BL.jpg",
                            Isbn = "9783161484121"
                        },
                        new
                        {
                            Titolo = "Assassinio sull'Orient Express",
                            Anno = 1934,
                            Autore = "Agatha Christie",
                            Genere = "Giallo",
                            Img = "https://m.media-amazon.com/images/I/71-n8WO0HFL._AC_UF1000,1000_QL80_.jpg",
                            Isbn = "9783161484122"
                        },
                        new
                        {
                            Titolo = "I promessi sposi",
                            Anno = 1842,
                            Autore = "Alessandro Manzoni",
                            Genere = "Storico",
                            Img = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/I_promessi_sposi_-_2nd_edition_cover.jpg/643px-I_promessi_sposi_-_2nd_edition_cover.jpg",
                            Isbn = "9783161484123"
                        },
                        new
                        {
                            Titolo = "Le grandi battaglie di Roma antica",
                            Anno = 2002,
                            Autore = "Andrea Frediani",
                            Genere = "Storico",
                            Img = "https://www.ibs.it/images/9788854144026_0_536_0_75.jpg",
                            Isbn = "9783161484124"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
